## Урок 4 ДЗ (04.03.2021)

* [Теория](#theor)
* [Практическое задание. ДЗ.](#ex)
    * [Задание 1](#ex1)
    * [Задание 2](#ex2)
    * [Задание 3](#ex3)
    * [Задание 4](#ex4)
    * [Задание 5](#ex5)

# <center>Теория <a class="anchor" id="theor"></a><center>

### Непрерывные случайные величины.

### Функция распределения и плотность распределения вероятностей.

### Равномерное и нормальное распределение. Центральная предельная теорема

**Непрерывная случайная величина** может принимать все возможные значения, содержащиеся на промежутке, который может быть как конечным (ограниченным), так и бесконечным.

**Функция распределения вероятностей** — это функция $F(x)$, которая для каждого значения $x$ показывает, какова вероятность того, что случайная величина меньше $x$.

**Плотность распределения вероятностей** — это функция $f(x)$, которая равна производной функции распределения вероятностей:

$$f(x) = F'(x)$$

#### Равномерное распределение

Распределение вероятностей случайной величины $X$ в зависимости от плотности:

$$f(x) = \begin{cases} 0, если \; x \le a; \\ \frac{1}{b - a}, если \; a < x \le b; \\ 0, \; если \; x > b. \end{cases}$$

Математическое ожидание $M(X)$ равномерно распределенной непрерывной случайной величины можно вычислить по формуле:

$$M(X) = \frac{a + b}{2}$$

По следующей формуле можно рассчитать дисперсию $D(X)$:


$$D(X) = \frac{(b - a)^2}{12}$$

Посмотрим на график плотности равномерного распределения:

<img src='https://ru.files.fm/thumb_show.php?i=4whssuky&view' width=500>Рис. 1 График плотности равномерного распределения</img>

График функции равномерного распределения:

<img src='https://ru.files.fm/thumb_show.php?i=fwy7dghu&view' width=500>Рис. 2 График функции равномерного распределения</img>

#### Нормальное распределение

Нормальное распределение — это распределение вероятностей непрерывной случайной величины $X$, плотность вероятности которой подчиняется формуле:

$$f(x) = \frac{1}{\sigma \sqrt{2 \pi}} e ^ {- \frac{(x - a)^2}{2 \sigma^2}},$$

---



где $a = M(X), \; \sigma^2 = D(X).$

График плотности нормального распределения имеет колоколообразную форму:

<img src='https://ru.files.fm/thumb_show.php?i=wmq8yuhw&view' width=500> </img> Рис 3. График плотности нормального распределения

Примеры нормально распределенных величин: рост и вес людей, скорость движение молекул в газах и жидкостях, показатели IQ.

Одно из свойств нормального распределения: среднее значение, медиана и мода совпадают.

На отрезке от $-\sigma$ до $+\sigma$ расположено около 68 % наблюдений,

от $-2\sigma$ до $+2\sigma$ — 95.4 %,

и от $-3\sigma$ до $+3\sigma$ — 99.72 %.

**Пример 1**

Расмотрим конкретный пример данных, распределенных нормально, — из статьи
<a href='https://habr.com/post/301340/'>«Рост хоккеистов: анализируем данные всех чемпионатов мира в текущем веке»</a>.

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('csv/hockey_players.csv', encoding='cp1251', parse_dates=['birth'])

FileNotFoundError: ignored

Просмотрим первые строки датасета:

In [ ]:
df.head()

NameError: ignored

Посмотрим количество строк, полей и информацию о полях в датасете:

In [ ]:
df.shape

NameError: ignored

In [ ]:
df.columns

In [ ]:
df.describe()

Удалим дубликаты:

In [ ]:
df = df.drop_duplicates(['name', 'birth'])

In [ ]:
df.shape

Построим распределение роста среди хоккеистов:

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
plt.hist(df['height'], bins=20)
plt.show()

NameError: ignored

На гистограмме видим характерное — похожее на колокол — нормальное распределение, так как мы знаем, что рост — одна из величин, которые могут распределяться нормально. Посмотрим отдельно статистики распределения роста хоккеистов.

Среднее значение:

In [ ]:
df['height'].mean()

Медиана:

In [ ]:
df['height'].median()

Мода (специально для этого показателя предварительно округлим значения роста до целых):

In [ ]:
df['height_rounded'] = df['height'].apply(round)
df['height_rounded'].head(10)

In [ ]:
df['height'].mode()

Видим, что значения среднего, медианы и моды достаточно близки. При большем количестве наблюдений и хорошем приближении к нормальному распределению эти величины могли бы быть приблизительно равны.

Среднее квадратичное отклонение:

In [ ]:
df['height'].std()

Дисперсия:

In [ ]:
df['height'].var()

NameError: ignored

#### Центральная предельная теорема

Центральные предельные теоремы — класс теорем в теории вероятностей. Они утверждают, что сумма достаточно большого количества слабо зависимых случайных величин, имеющих примерно одинаковые масштабы (ни одно из слагаемых не доминирует, не вносит в сумму определяющего вклада), имеет распределение, близкое к нормальному.

Если у нас есть несколько выборок из генеральной совокупности (то есть из совокупности всех возможных объектов исследования), то среднее по этим выборкам также будет иметь нормальное распределение.

Другими словами, среднее достаточно большого числа независимых и нормально распределенных случайных величин также является приблизительно нормально распределенным.

Если $x_1, x_2, ..., x_n$ — случайные величины с математическим ожиданием (или средним значением) $\mu$ и стандартным отклонением $\sigma$, и при этом $n$ — большое число, то $\frac{1}{n}(x_1 + x_2 + ... + x_n)$ — приближенно нормально распределенная величина с математическим ожиданием $\mu$ и стандартным отклонением, равным $\frac{\sigma}{\sqrt(n)}$.

**Пример 2**

Из имеющегося набора данных с ростом хоккеистов сформируем 300 выборок по 10 наблюдений и рассмотрим распределение средних значений:

In [ ]:
np.random.seed(42)

In [ ]:
samples = []

In [ ]:
for i in range(300):
    sample = df.loc[:, 'height'].sample(n=10).values
    samples.append(sample)

NameError: ignored

Вычислим средние значения для каждой выборки:

In [ ]:
mean_values = []

In [ ]:
for sample in samples:
    mean_values.append(sample.mean())

In [ ]:
len(mean_values)

In [ ]:
mean_values = np.array(mean_values)

In [ ]:
mean_values

In [ ]:
plt.hist(mean_values, bins=10)
plt.show()

По гистограмме видно: количество наблюдений недостаточно большое, но распределение похоже на нормальное.

## <center>Практическое задание <a class="anchor" id="ex"></a><center>

### Задание 1 <a class="anchor" id="ex1"></a>

Случайная непрерывная величина A имеет равномерное распределение на промежутке (200, 800].
Найдите ее среднее значение и дисперсию.

### Решение

Математическое ожидание $M(X)$ равномерно распределенной непрерывной случайной величины:

$$M(X) = \frac{a + b}{2} = \frac{200 + 800}{2} = 500$$

In [ ]:
(200+800)/2

500.0

Дисперсия $D(X)$:

$$D(X) = \frac{(b - a)^2}{12} = \frac{(800 - 200)^2}{12} = 30000$$

In [ ]:
(800-200)**2/12

30000.0

### Задание 2 <a class="anchor" id="ex2"></a>

О случайной непрерывной равномерно распределенной величине B известно, что ее дисперсия равна 0.2.
Можно ли найти правую границу величины B и ее среднее значение зная, что левая граница равна 0.5?
Если да, найдите ее.

### Решение

$$f(x) = \begin{cases} 0, если \; x \le a; \\ \frac{1}{b - a}, если \; a < x \le b; \\ 0, \; если \; x > b. \end{cases}$$

$$D(X) = \frac{(b - a)^2}{12} = \frac{(b - 0.5)^2}{12} = 0.2$$

$$(b - 0.5)^2 = 2.4$$

$$b-0.5 = ^+_-1.5492$$

$$b_{1,2} = 0.5 ^+_-1.5492$$

$$b_1 = -1.0492 \,\,\, \& \,\,\, b_2 = 2.0492$$

$$a = 0.5 \ll b \Rightarrow b = 2.0492$$

$$ M(X) = \frac{0.2+2.049}{2} = 1.1246$$

In [ ]:
import numpy as np
s=np.sqrt(2.4)
b=0.5+s
b
a=0.2
m=(a+b)/2
m

1.1245966692414835

### Задание 3 <a class="anchor" id="ex4"></a>

Непрерывная случайная величина X распределена нормально и задана плотностью распределения

f(x) = (1 / (4 * sqrt(2*pi))) * (exp(-((x+2)**2) / 32))

Найдите:

а). M(X)

б). D(X)

в). std(X) (среднее квадратичное отклонение)

### Решение

Нормальное распределение — это распределение вероятностей непрерывной случайной величины $X$, плотность вероятности которой подчиняется формуле:

$$f(x) = \frac{1}{\sigma \sqrt{2 \pi}} e ^ {- \frac{(x - \alpha)^2}{2 \sigma^2}} = \frac{1}{4 \sqrt{2 \pi}} e ^ {- \frac{(x + 2)^2}{32}} = \frac{1}{4 \sqrt{2 \pi}} e ^ {- \frac{(x - (- 2))^2}{2 \cdot 4^2}}$$

а). $M(X) = \alpha = -2$

б). $D(X) = \sigma^2  = 4^2 = 16$

в). Среднее квадратичное отклонение $std(X) = \sigma = \sqrt{|D(X)|} = 4$

### Задание 4 <a class="anchor" id="ex4"></a>

Рост взрослого населения города X имеет нормальное распределение.

Причем, средний рост равен 174 см, а среднее квадратичное отклонение равно 8 см.
Какова вероятность того, что случайным образом выбранный взрослый человек имеет рост:

а). больше 182 см

б). больше 190 см

в). от 166 см до 190 см

г). от 166 см до 182 см

д). от 158 см до 190 см

е). не выше 150 см или не ниже 190 см

ё). не выше 150 см или не ниже 198 см

ж). ниже 166 см.

### Решение

Для расчета вероятностей можно также воспользоваться таблицами нормального распределения:

[SixSigmaOnline.ru / три Z-таблицы (левая - правая - отрицательные зн-я)](http://sixsigmaonline.ru/baza-znanij/37-1-0-36)

In [ ]:
import numpy as np
sigma = 8 # среднеквадратичное отклонение
mo = 174  # математическое ожидание
n = 100000000  # размер массива
np.random.seed(25)
a = sigma * np.random.randn(n) + mo

а). больше 182 см

$$от \,\, \frac{182-174}{8} = 1 \sigma$$

Из "Z-таблицы" при $Z=1$ следует вероятность $0.15866$ (правая сторона, так как верхняя граница до $\infty$)

In [ ]:
a[a>182].shape[0]/a.shape[0]

0.15869536

б). больше 190 см

$$от \,\, \frac{190-174}{8} = 2 \sigma$$

Из "Z-таблицы" при $Z=2$ следует вероятность $0.02275$ (правая сторона)

In [ ]:
a[a>190].shape[0]/a.shape[0]

0.02274998

в). от 166 см до 190 см

$$от \,\, \frac{166-174}{8}=-1 \sigma \,\, \Rightarrow 0.1587  \, \, (отриц. \, зн-я)$$

$$до \,\,  \frac{190-174}{8}= 2 \sigma  \,\, \Rightarrow 0.9772 \, \, (левая \, сторона)$$

Следовательно вероятность $0.9772 - 0.1587 = 0.8185$

In [ ]:
t=0.9772-0.1587
t

0.8185

In [ ]:
a[(a >= 166) & (a <= 190)].shape[0]/a.shape[0]

0.81862783

г). от 166 см до 182 см

$$от \, \frac{166-174}{8} = -1 \sigma \,\, \Rightarrow 0.1587  \, \, (отриц. \, зн-я)$$

$$до \, \, \frac{182-174}{8} =1 \sigma \,\, \Rightarrow 0.8413 \, \, (левая \, сторона)$$

Следовательно вероятность $0,8413 - 0.1587 = 0.6826$

In [ ]:
t=0.8413-0.1587
t

0.6826000000000001

In [ ]:
a[(a >= 166) & (a <= 182)].shape[0]/a.shape[0]

0.68268245

д). от 158 см до 190 см

$$от \, \frac{158-174}{8} = -2 \sigma \,\, \Rightarrow 0.0228  \, \, (отриц. \, зн-я)$$

$$до \, \, \frac{190-174}{8} =2 \sigma \,\, \Rightarrow 0.9772 \, \, (левая \, сторона)$$

Следовательно вероятность $0.9772 - 0.0228 = 0.9544$

In [ ]:
t=0.9772 - 0.0228
t

0.9543999999999999

In [ ]:
a[(a >= 158) & (a <= 190)].shape[0]/a.shape[0]

0.9544835

е). не выше 150 см или не ниже 190 см

$$до \, \, \frac{150-174}{8} =-3 \sigma \,\, \Rightarrow 0.0013 \, \, (отриц. \, зн-я)$$

$$от \, \frac{190-174}{8} = 2 \sigma \,\, \Rightarrow 0.02275  \, \, (правая \, сторона)$$

Следовательно вероятность $0.02275 - 0.0013 = 0.2145$

In [ ]:
t=0.02275 - 0.0013
t

0.02145

In [ ]:
a[(a <= 150) + (a >= 190)].shape[0]/a.shape[0]

0.02410641

In [ ]:
a[(a >= 190)].shape[0]/a.shape[0] - a[(a <= 150)].shape[0]/a.shape[0]

0.02139355

ё). не выше 150 см или не ниже 198 см

$$до \, \, \frac{150-174}{8} =-3 \sigma \,\, \Rightarrow 0.0013 \, \, (отриц. \, зн-я)$$

$$от \, \frac{198-174}{8} = 3 \sigma \,\, \Rightarrow 0.00135  \, \, (правая \, сторона)$$

Следовательно вероятность $0.00135 - 0.0013 = 5.000000000000013e-05$

In [ ]:
t=0.00135-0.0013
t

5.000000000000013e-05

In [ ]:
a[(a <= 150) + (a >= 198)].shape[0]/a.shape[0]

0.00270723

ж). ниже 166 см.

$$до \,\, \frac{166 - 174}{8} = -1 \sigma$$

при $Z=-1$ следует вероятность $0.1587$

In [ ]:
a[a<166].shape[0]/a.shape[0]

0.15862219

### Задание 5 <a class="anchor" id="ex5"></a>

На сколько сигм (средних квадратичных отклонений) отклоняется рост человека, равный 190 см, от
математического ожидания роста в популяции, в которой M(X) = 178 см и D(X) = 25 кв.см?

### Решение

Среднее квадратичное отклонение $$std(X) = \sigma = \sqrt{|D(X)|} = \sqrt{25} = 5$$

$$\frac{190-178}{5} = 2.4 \sigma \Rightarrow \, \, на \, \, 2.4 \sigma$$

In [ ]:
(190-178)/5

2.4